Repository sunny0826/kubecm, pull requests merged in 2023-12, with the labels that each got.

#799 feat: Added an additional alias to the switch command
  cmd/switch.go
Labels: kind/feature, size/XS

#796 feat: Allow silencing context table print upon config write
  cmd/root.go
  cmd/utils.go
  docs/en-us/cli/kubecm.md
  docs/en-us/cli/kubecm_add.md
  docs/en-us/cli/kubecm_alias.md
  docs/en-us/cli/kubecm_clear.md
  docs/en-us/cli/kubecm_cloud.md
  docs/en-us/cli/kubecm_cloud_add.md
  docs/en-us/cli/kubecm_cloud_list.md
  docs/en-us/cli/kubecm_completion.md
  docs/en-us/cli/kubecm_create.md
  docs/en-us/cli/kubecm_delete.md
  docs/en-us/cli/kubecm_export.md
  docs/en-us/cli/kubecm_list.md
  docs/en-us/cli/kubecm_merge.md
  docs/en-us/cli/kubecm_namespace.md
  docs/en-us/cli/kubecm_rename.md
  docs/en-us/cli/kubecm_switch.md
  docs/en-us/cli/kubecm_version.md
Labels: kind/feature, size/M

#793 docs: added documentations and help message for setup completions when used as kubectl plugin
  cmd/completion.go
  docs/en-us/cli/kubecm_completion.md
  docs/zh-cn/cli/kubecm_completion.md
  hack/kubectl-plugin-completion/kubectl_complete-kc.sh
Labels: kind/feature, size/L

#824 update docs
  docs/README.md
  docs/en-us/README.md
  docs/zh-cn/README.md
  docs/zh-cn/cli/kubecm.md
  docs/zh-cn/cli/kubecm_add.md
  docs/zh-cn/cli/kubecm_alias.md
  docs/zh-cn/cli/kubecm_clear.md
  docs/zh-cn/cli/kubecm_cloud.md
  docs/zh-cn/cli/kubecm_cloud_add.md
  docs/zh-cn/cli/kubecm_cloud_list.md
  docs/zh-cn/cli/kubecm_completion.md
  docs/zh-cn/cli/kubecm_create.md
  docs/zh-cn/cli/kubecm_delete.md
  docs/zh-cn/cli/kubecm_export.md
  docs/zh-cn/cli/kubecm_list.md
  docs/zh-cn/cli/kubecm_merge.md
  docs/zh-cn/cli/kubecm_namespace.md
  docs/zh-cn/cli/kubecm_rename.md
  docs/zh-cn/cli/kubecm_switch.md
  docs/zh-cn/cli/kubecm_version.md
Labels: kind/documentation, size/S

#825 refactor: 💡 update go version to 1.20
  .github/workflows/e2e-test.yaml
  .github/workflows/go.yaml
  .github/workflows/release.yaml
  go.mod
Labels: kind/feature, size/S

#826 ci: 🎡 update e2e test
  .github/workflows/e2e-test.yaml
Labels: kind/documentation, size/XS

#827 Update SECURITY.md
  SECURITY.md
Labels: kind/documentation

#828 Update SECURITY.md
  SECURITY.md
Labels: kind/documentation, size/XS

#829 Update LICENSE
  LICENSE
Labels: kind/documentation, size/XS
