Repository sunny0826/kubecm, pull requests merged in 2024-06, with the labels that each got.

#962 feat: allow specify the context to be added
  cmd/add.go
  cmd/add_test.go
  cmd/cloud_add.go
  cmd/merge.go
  docs/en-us/cli/kubecm_add.md
  docs/en-us/cli/kubecm_merge.md
  docs/zh-cn/cli/kubecm_add.md
  docs/zh-cn/cli/kubecm_merge.md
  go.mod
Labels: kind/feature, size/L

#967 fixing issue #888
  cmd/add.go
  cmd/merge.go
  cmd/root.go
  cmd/utils.go
  cmd/utils_test.go
Labels: kind/documentation, size/L

#973 add KUBECM_DISABLE_K8S_MORE_INFO env to disable output moreinfo
  cmd/list.go
  cmd/utils.go
Labels: kind/feature, size/XS

#977 update README & docs
  README.md
  docs/_coverpage.md
  docs/_navbar.md
  docs/en-us/README.md
  docs/en-us/cli/kubecm.md
  docs/en-us/cli/kubecm_add.md
  docs/en-us/cli/kubecm_add_docs.md
  docs/en-us/cli/kubecm_alias.md
  docs/en-us/cli/kubecm_alias_docs.md
  docs/en-us/cli/kubecm_clear.md
  docs/en-us/cli/kubecm_clear_docs.md
  docs/en-us/cli/kubecm_cloud.md
  docs/en-us/cli/kubecm_cloud_add.md
  docs/en-us/cli/kubecm_cloud_docs.md
  docs/en-us/cli/kubecm_cloud_list.md
  docs/en-us/cli/kubecm_create.md
  docs/en-us/cli/kubecm_delete.md
  docs/en-us/cli/kubecm_delete_docs.md
  docs/en-us/cli/kubecm_docs.md
  docs/en-us/cli/kubecm_export.md
  docs/en-us/cli/kubecm_export_docs.md
  docs/en-us/cli/kubecm_list.md
  docs/en-us/cli/kubecm_list_docs.md
  docs/en-us/cli/kubecm_merge.md
  docs/en-us/cli/kubecm_merge_docs.md
  docs/en-us/cli/kubecm_rename.md
  docs/en-us/cli/kubecm_rename_docs.md
  docs/en-us/cli/kubecm_switch.md
  docs/en-us/cli/kubecm_switch_docs.md
  docs/en-us/cli/kubecm_version.md
  docs/en-us/install.md
  docs/en-us/introduction.md
  docs/static/interaction-lates.gif
  docs/static/lates.gif
  docs/static/ns-lates.gif
Labels: kind/documentation, size/M
