Repository sunny0826/kubecm, pull requests merged in 2024-01, with the labels that each got.

#835 Add shorthand letter for `--ui-size`
  cmd/root.go
Labels: kind/feature, size/XS

#836 chore: 🤖 add allcontributors
  .all-contributorsrc
Labels: kind/documentation, size/S

#837 Fix `delete` removes user even if another context is using it
  cmd/delete.go
  cmd/delete_test.go
Labels: kind/bug, size/M

#839 feat: 🎸 add docs command
  cmd/add.go
  cmd/alias.go
  cmd/clear.go
  cmd/cloud.go
  cmd/cmd.go
  cmd/delete.go
  cmd/docs.go
  cmd/export.go
  cmd/list.go
  cmd/merge.go
  cmd/namespace.go
  cmd/rename.go
  cmd/switch.go
  go.mod
  go.sum
Labels: kind/documentation, size/M

#844 chore: 🤖 add pr template
  .github/pull_request_template.md
Labels: kind/documentation, size/S

#846 docs: ✏️ add contribute docs
  .all-contributorsrc
  README.md
  docs/en-us/contribute.md
  docs/zh-cn/contribute.md
Labels: kind/documentation, size/L

#847 feat: bump to use go1.21
  .github/workflows/e2e-test.yaml
  .github/workflows/go.yaml
  .github/workflows/release.yaml
  go.mod
  go.sum
Labels: kind/feature, size/M

#849 chore: remove `varcheck` check
  .golangci.yml
Labels: kind/documentation, size/XS

#851 ci: 🎡 update release action
  .github/workflows/release.yaml
Labels: kind/documentation, size/XS

#854 ci: 🎡 fix codeql action
  .github/workflows/codeql-analysis.yml
Labels: kind/documentation, size/XS

#855 feat: 🎸 get export env KUBECONFIG
  .github/workflows/e2e-test.yaml
  cmd/root.go
  cmd/utils.go
Labels: kind/feature, size/S

#856 fix: 🐛 Unable to switch to a namespace
  .github/workflows/e2e-test.yaml
  cmd/namespace.go
  cmd/namespace_test.go
  cmd/utils.go
Labels: kind/bug, size/L

#864 feat: 🎸 rewrite create commands
  .github/workflows/e2e-test.yaml
  .gitignore
  cmd/create.go
  cmd/create_test.go
  docs/en-us/cli/kubecm_create.md
Labels: kind/feature, size/L

#865 docs: ✏️ update README
  README.md
Labels: kind/documentation, size/M

#868 docs: ✏️ fix install docs
  docs/en-us/install.md
  docs/zh-cn/install.md
Labels: kind/documentation, size/S

#875 Fix routing on website
  docs/404.html
  docs/index.html
Labels: kind/documentation, size/M
